export const REGISTER_INSTANCE = 'REDUX-COMPONENTS/REGISTER_INSTANCE';
export const PARENT_INSTANCE = 'REDUX-COMPONENTS/PARENT_INSTANCE';
export const UNREGISTER_INSTANCE = 'REDUX-COMPONENTS/UNREGISTER_INSTANCE';
export const COMPONENT_ACTION = 'REDUX-COMPONENTS/COMPONENT_ACTION';
